name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  pubspec_version_extractor:
    path: ../

dev_dependencies:
  build_runner: ^2.5.0

pubspec_version_extractor:
  output: lib/config
  