name: pubspec_version_extractor
description: Extract version from pubspec.yaml to Dart code.
version: 1.1.3
repository: https://github.com/thanhle1547/pubspec_version_extractor

environment:
  sdk: ^3.7.0

dependencies:
  args: ^2.4.2
  build: ^3.0.0
  code_builder: ^4.10.1
  dart_style: ^3.0.0
  frontend_server_client: '>=3.2.0 <5.0.0'
  path: ^1.8.3
  tint: ^2.0.1
  yaml: ^3.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  test_descriptor: ^2.0.1
  test_process: ^2.1.0
  pubspec_parse: ^1.2.3

executables:
  pubspec_version_extractor: