name: pubspec_version_extractor
description: Extract version from pubspec.yaml to Dart code.
version: 1.0.0
repository: https://github.com/thanhle1547/pubspec_version_extractor

environment:
  sdk: ^3.0.0

dependencies:
  build: ^2.4.1
  code_builder: ^4.9.0
  dart_style: ^2.3.4
  path: ^1.8.3
  tint: ^2.0.1
  yaml: ^3.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  test_descriptor: ^2.0.1
  test_process: ^2.1.0
  pubspec_parse: ^1.2.3
